### PR TITLE
Bug 1288154 - implement get_pings using the Dataset api

### PR DESCRIPTION
**Pull request by maurodoglio**
See individual commits messages

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_moztelemetry/78)

### CODE REVIEW

**Comment by chutten** [comment]
I didn't see anything egregiously out-of-place, but then this is the first patch I've reviewed against this lib so I'm mostly looking for my own benefit :)

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-:-KOfbLKk7VlO9q3IOkY6:b-j6ziy4)*

**Comment by vitillo** [comment]
Has this been manually tested with the Tutorial notebook? If not, you might want to set disable sampling for that test.

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[docs/userguide.rst, line 26 \[r8\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjWWEl9-4Tuzy8yZNU:-KOjWWEl9-4Tuzy8yZNV:b4oi8wm) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/0f0852aa603b43c1520a4c8b43d63c679aecbd6b/docs/userguide.rst#L26)):*
> ```reStructuredText
> Using Spark RDDs
> ----------------
> Both ``Dataset`` and ``get_pings`` return the data as a `Spark RDD <http://spark.apache.org/docs/latest/programming-guide.html#resilient-distributed-datasets-rdds>`_.
> ```

I would avoid mentioning `get_pings` since we want people to move away from it.

---

*[moztelemetry/spark.py, line 24 \[r2\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjT0d_nHSDO4AdXxy8:-KOjT0daJeCMpX4gaYUK:b-ehdo0l) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/f1ed1adbeb82eb8d0768d675cdf691652b127dd6/moztelemetry/spark.py#L24)):*
> ```Python
> from filter_service import SDB
> from histogram import Histogram
> from moztelemetry.heka_message_parser import parse_heka_message
> ```

Why is this change needed here?

---

*[moztelemetry/spark.py, line 110 \[r2\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjTLHdA7QiZufCJUfm:-KOjTLHdA7QiZufCJUfn:b-ozh07p) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/f1ed1adbeb82eb8d0768d675cdf691652b127dd6/moztelemetry/spark.py#L110)):*
> ```Python
> 
>     dataset = Dataset.from_source('telemetry') \
>                      .where(docType=doc_type) \
> ```

I think this is not going to work if the users passes `docType=None` as argument. Same below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-:-KOjUjxIiIYGIUv5TblK:b-cejt7e)*

**Comment by maurodoglio** [comment]
It hasn't yet. I'm looking into that now.

---

Review status: 1 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/userguide.rst, line 26 \[r8\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjWWEl9-4Tuzy8yZNU:-KOjfWUkEceoi4WRUrE7:b6dro3) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/0f0852aa603b43c1520a4c8b43d63c679aecbd6b/docs/userguide.rst#L26)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I would avoid mentioning `get_pings` since we want people to move away from it.
</details>
What if I mark it as deprecated? I would rather do that than keeping it undocumented.

---

*[moztelemetry/spark.py, line 24 \[r2\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjT0d_nHSDO4AdXxy8:-KOjvevpWiFR0pDvJS2r:b4cwram) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/f1ed1adbeb82eb8d0768d675cdf691652b127dd6/moztelemetry/spark.py#L24)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Why is this change needed here?
</details>
It's not! good catch :smile: 

---

*[moztelemetry/spark.py, line 110 \[r2\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjTLHdA7QiZufCJUfm:-KOjvioH33Di9JLc1WCE:b-8fyjfp) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/f1ed1adbeb82eb8d0768d675cdf691652b127dd6/moztelemetry/spark.py#L110)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I think this is not going to work if the users passes `docType=None` as argument. Same below.
</details>
Fixed and refactored

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-:-KOjvrWCUgKoOI4FoiF3:bhhqtt6)*

**Comment by maurodoglio** [comment]
I checked the hello world notebook and the ping counts are the same.

---

Review status: 1 of 13 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-:-KOk_oFf0M_jITXigsnX:b-ip01qw)*

**Comment by maurodoglio** [comment]
Review status: 1 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[moztelemetry/spark.py, line 24 \[r2\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjT0d_nHSDO4AdXxy8:-KOka0zYaBoSOBVEyAjx:b-896fix) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/f1ed1adbeb82eb8d0768d675cdf691652b127dd6/moztelemetry/spark.py#L24)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> It's not! good catch :smile: 
</details>
Done.

---

*[moztelemetry/spark.py, line 110 \[r2\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjTLHdA7QiZufCJUfm:-KOka3gDV6gQquXQV7It:b-896fix) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/f1ed1adbeb82eb8d0768d675cdf691652b127dd6/moztelemetry/spark.py#L110)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> Fixed and refactored
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78)*

**Comment by vitillo** [comment]
Reviewed 1 of 4 files at r3, 1 of 12 files at r10, 1 of 2 files at r13, 1 of 1 files at r17.
Review status: 4 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/userguide.rst, line 26 \[r8\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjWWEl9-4Tuzy8yZNU:-KOoLtO8VrgAXIXz4Zjo:b-ba7jcz) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/0f0852aa603b43c1520a4c8b43d63c679aecbd6b/docs/userguide.rst#L26)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> What if I mark it as deprecated? I would rather do that than keeping it undocumented.
</details>
Sounds good to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78)*

**Comment by maurodoglio** [comment]
Review status: 3 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/userguide.rst, line 26 \[r8\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-KOjWWEl9-4Tuzy8yZNU:-KOti3XNTTNSVb2YvWbP:b-896fix) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/0f0852aa603b43c1520a4c8b43d63c679aecbd6b/docs/userguide.rst#L26)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Sounds good to me.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r18.
Review status: 4 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78#-:-KOx1m7G-v4TsojuYNyc:bnfp4nl)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r15.
Review status: 5 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78)*

**Comment by vitillo** [comment]
Reviewed 3 of 4 files at r11, 1 of 2 files at r13, 2 of 2 files at r14, 2 of 2 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/78)*

**Comment by vitillo** [comment]
@maurodoglio Great job! Please upload the new version to pypi.

**Pull request merged**
