### PR TITLE
Bug 1251631 - remove getpings v2

### PR DESCRIPTION
**Pull request by maurodoglio**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_moztelemetry/74)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/74#-:-KNC_oiXFyE6tBSV7nWY:1417088721)*

**Comment by vitillo** [comment]
Please increase the version number in setup.py before merging it.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/74#-:-KNC_qwUjmFPAJP8GMXA:-771803147)*

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/74)*

**Comment by vitillo** [comment]
:lgtm: Please merge and redeploy.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/74#-:-KNlmUC5z67JjM6CkbQb:1138758460)*

**Comment by vitillo** [comment]
@maurodoglio please redeploy

**Pull request merged**
