### PR TITLE
Bug 1331005 - Support GPU process histograms/keyedHistograms in get_pings_properties

### PR DESCRIPTION
**Pull request by gw280**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_moztelemetry/104)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by maurodoglio** [comment]
Sorry this is taking so long. This is one of the code paths that has no test coverage, I want to make sure it doesn't break anything.

**Comment by maurodoglio** [comment]
The code looks correct, I'm only worried about overlapping [keyed]histogram names between content processes and gpu processes. Maybe we should add yet another switch to get_ping_properties to tell whether we want the children [keyed]histogram separated by process type. @vitillo @fbertsch any opinion on that?

**Comment by vitillo** [comment]
Since this function will very likely be rewritten in the near future I am leaning towards accepting this PR as is.

**Comment by maurodoglio** [comment]
@gw280 before I merge it, may I ask you if you verified that it works?

**Comment by gw280** [comment]
Yes, I tested it on a telemetry analysis instance.

**Comment by maurodoglio** [comment]
Please rebase it on top of latest master

**Comment by gw280** [comment]
Done

**Comment by maurodoglio** [comment]
Thanks for the patch @gw280 😃

**Pull request merged**
