### PR TITLE
Bug 1315243 - fix  multiple range filters in get_pings

### PR DESCRIPTION
**Pull request by maurodoglio**
This is using partial functions to store the correct range filter
values.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_moztelemetry/87)

### CODE REVIEW

**Comment by maurodoglio** [comment]
@vitillo r?

**Comment by vitillo** [comment]
lgtm

**Comment by vitillo** [comment]
@maurodoglio please increase the version number

**Comment by vitillo** [comment]
@maurodoglio looks like some tests are failing

**Pull request merged**
