### PR TITLE
Bug 1292111 - Add sample parameter to Dataset.records

### PR DESCRIPTION
**Pull request by maurodoglio**
This is needed to have feature parity with get_pings

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_moztelemetry/77)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[moztelemetry/dataset.py, line 159 \[r1\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/77#-KOKVH9QKOo6qLuo4SeA:-KOKVH9QKOo6qLuo4SeB:108660481) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/c69802b91bc25052570a87044797997ad07b7086/moztelemetry/dataset.py#L159)):*
> ```Python
>         retrieved
>         :param sample: percentage of results to return. Useful to return
>         a representative sample of the dataset.
> ```

It's not necessarily representative as it's sampling the files and not the records within it (we should mention that in the documentation); furthermore, if used with the limit parameter, it's even less so as a S3 scan returns the files in alphabetical order. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/77)*

**Comment by maurodoglio** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[moztelemetry/dataset.py, line 159 \[r1\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/77#-KOKVH9QKOo6qLuo4SeA:-KOKZebi22a_rB_5u76c:566930310) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/c69802b91bc25052570a87044797997ad07b7086/moztelemetry/dataset.py#L159)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> It's not necessarily representative as it's sampling the files and not the records within it (we should mention that in the documentation); furthermore, if used with the limit parameter, it's even less so as a S3 scan returns the files in alphabetical order. 
</details>
I'll change the wording here, and I'll add that the using the limit parameter disables the sampling

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/77)*

**Comment by maurodoglio** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[moztelemetry/dataset.py, line 159 \[r1\]](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/77#-KOKVH9QKOo6qLuo4SeA:-KOKd_AeVgVoX6xmhnSv:-499146009) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/c69802b91bc25052570a87044797997ad07b7086/moztelemetry/dataset.py#L159)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> I'll change the wording here, and I'll add that the using the limit parameter disables the sampling
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/77)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/77#-:-KOKeuNpb9Fgay56pB9e:1417088721)*

**Pull request merged**
