### PR TITLE
Bug 1305757 - Categorical histo support

### PR DESCRIPTION
**Pull request by fbertsch**
@vitillo r?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_moztelemetry/85)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[moztelemetry/histogram.py, line 129 at r2](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-KTioorwGQzkpeTeiC67:-KTioorxl1CSODNUNysI:bablm24) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/edfeced49e353e2a9b8867f610992e43e1aa2334/moztelemetry/histogram.py#L129)):*
> ```Python
>         self.kind = self.definition.kind()
>         self.name = name
>         self.labels = self.definition.labels()
> ```

The idea of this class is that it uses a pandas series to represent a histogram internally, so you should store the labels as the index of said series.

---

*[tests/test_histogram.py, line 46 at r2](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-KTip-Cz40PHQ3yP-BUg:-KTip-Cz40PHQ3yP-BUh:b-d9y8xb) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/edfeced49e353e2a9b8867f610992e43e1aa2334/tests/test_histogram.py#L46)):*
> ```Python
>                -1, -1])
> 
> def test_categorical_histogram():
> ```

I think we should move this test and the others to use pytest as the rest of the test suite.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_histogram.py, line 46 at r2](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-KTip-Cz40PHQ3yP-BUg:-KTjC3d5U5307hM-bV-1:b-81m370) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/edfeced49e353e2a9b8867f610992e43e1aa2334/tests/test_histogram.py#L46)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I think we should move this test and the others to use pytest as the rest of the test suite.
</details>
Please ignore this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85)*

**Comment by fbertsch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[moztelemetry/histogram.py, line 129 at r2](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-KTioorwGQzkpeTeiC67:-KTjWoBeeE3Xlgjf0T7L:bmxfilz) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/edfeced49e353e2a9b8867f610992e43e1aa2334/moztelemetry/histogram.py#L129)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> The idea of this class is that it uses a pandas series to represent a histogram internally, so you should store the labels as the index of said series.
</details>
Done. Added tests to ensure that this different functionality behaves as expecting for the various class functions. At some point we can consider using inheritance for this instead of all these if statements. Would also prevent changes from affecting other histogram types.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85)*

**Comment by fbertsch** [comment]
@vitillo RFAL

**Comment by vitillo** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_histogram.py, line 51 at r4](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-KTns6KhisbZIq82U74J:-KTns6KiBYIx2Lj63GN6:bhx1sy2) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/0ddd850e120ef1cef0fa919dd14b40b57f176589/tests/test_histogram.py#L51)):*
> ```Python
> 
> def test_categorical_histogram():
>     series = pd.Series([2, 1, 0, 0], index=['CommonLabel', 'Label2', 'Label3', CATEGORICAL_HISTOGRAM_SPILL_BUCKET_NAME], dtype='int64')
> ```

No need to use for loops with series, i.e. you can use a vectorized operation to compare two pandas series.

---

*[tests/test_histogram.py, line 57 at r4](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-KTnseYx0Vo3SLx5sE-K:-KTnseYx0Vo3SLx5sE-L:brmqf7q) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/0ddd850e120ef1cef0fa919dd14b40b57f176589/tests/test_histogram.py#L57)):*
> ```Python
> 
> def test_cateogrical_histogram_value():
>     with pytest.raises(AssertionError):
> ```

This is incorrect. The test should fail only if the median is requested, otherwise the pandas series should be returned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85)*

**Comment by fbertsch** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_histogram.py, line 51 at r4](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-KTns6KhisbZIq82U74J:-KToN3ADBokkBch7ATHj:b-896fix) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/0ddd850e120ef1cef0fa919dd14b40b57f176589/tests/test_histogram.py#L51)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> No need to use for loops with series, i.e. you can use a vectorized operation to compare two pandas series.
</details>
Done.

---

*[tests/test_histogram.py, line 57 at r4](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-KTnseYx0Vo3SLx5sE-K:-KToN4N6UYtaPm3DKXwf:b-896fix) ([raw file](https://github.com/mozilla/python_moztelemetry/blob/0ddd850e120ef1cef0fa919dd14b40b57f176589/tests/test_histogram.py#L57)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> This is incorrect. The test should fail only if the median is requested, otherwise the pandas series should be returned.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85)*

**Comment by fbertsch** [comment]
Changes made - @vitillo RFAL

**Comment by vitillo** [comment]
Please bump the version.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-:-KTtWfIrTCewhy5JQw54:bz5fvpa)*

**Comment by fbertsch** [comment]
Done!

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-:-KTtYYGGTPYWPaHQ1wSo:b-896fja)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/85#-:-KTuE5Dy6VXTnz9WQG65:bnfp4nl)*

**Pull request merged**
