### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by maurodoglio**
Hey @fbertsch do you mind to take a look at this?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_moztelemetry/105)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by fbertsch** [comment]
@maurodoglio LGTM. If you want, you could clean these few flake8 issues up as well:
spark.py:267:68: E502 the backslash is redundant between brackets
spark.py:272:64: E502 the backslash is redundant between brackets
spark.py:273:25: E127 continuation line over-indented for visual indent
spark.py:282:101: E501 line too long (104 > 100 characters)

**Comment by maurodoglio** [comment]
RFAL

**Comment by maurodoglio** [comment]
argh

**Comment by maurodoglio** [comment]
Ok this looks so much better now. This is ready @fbertsch !

**Pull request merged**
