### PR TITLE
Bug 1317784 - Dataset.where should accept multiple parameters

### PR DESCRIPTION
**Pull request by maurodoglio**
This is using a partial function to store the filter value

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/python_moztelemetry/89)

### CODE REVIEW

**Comment by maurodoglio** [comment]
@fbertsch I added a test to cover what I think is your case, but it would be great if you could verify that this patch actually solves it 😄 
For extra karma points, could you please r?

**Comment by fbertsch** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/89#-:-KWhBHYgTu1BG8g3rNHt:bnfp4nl)*

**Comment by fbertsch** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/89)*

**Comment by fbertsch** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/python_moztelemetry/89)*

**Pull request merged**
