### PR TITLE
Bug 1341566 Regenerate protobuf classes

### PR DESCRIPTION
**Pull request by jklukas**
Also adds documentation on how to regenerate the classes in the future.

### CODE REVIEW

**Comment by fbertsch** [comment]
@jklukas have you tested this on some data from the data lake?

**Comment by jklukas** [comment]
> have you tested this on some data from the data lake?

I was relying on the heka tests to verify this update is working fine, but I can test on real data from the lake. I'm spinning up an ATMO cluster and I'll try out the telemetery hello world with these updates in place.

**Comment by fbertsch** [comment]
Be wary that the worker nodes will not have an updated version of this unless you ssh into them and updated the lib separately. I would test on a single node, reading a few small files should be enough.

**Comment by jklukas** [comment]
Good call on testing. I ssh'ed this updated file into the python environment and received an error in the Hello World notebook about not recognizing "serialized options". I'm pretty sure this just means we need an updated version of the `protobuf` library. Testing that out now, and we'll need to issue a follow-up PR to spark bootstrap to update moztelemetry and protobuf.

**Comment by jklukas** [comment]
Hello World is working with the code of this PR and updated pandas and protobuf. Will add in a lower bound on protobuf version.

**Comment by jklukas** [comment]
Ready for another look, @fbertsch.

**Pull request merged**
