### PR TITLE
Allow Histograms.json URL to be specified with get_pings_properties

### PR DESCRIPTION
**Pull request by poiru**
This is needed because we occasionally need to use histograms that have
been deleted from the mozilla-central Histograms.json.

### CODE REVIEW

**Comment by poiru** [comment]
@vitillo I decided to go with `histograms_url` (instead of `histograms_rev`) so that you can 1) copy paste the URL into your browser and 2) use a custom Histograms.json.

(I also tested this on a Spark cluster so I hopefully I don't break everything again!)

**Comment by vitillo** [comment]
You shouldn't change the current API as other projects depend on it, e.g. the [aggregator](https://github.com/mozilla/python_mozaggregator/blob/master/mozaggregator/db.py#L84) job. Any change you do should be backward compatible.

**Comment by poiru** [comment]
@vitillo OK, how about this? `histograms_url` takes precedence, but `revision` is still supported.

**Comment by vitillo** [comment]
I would like to avoid giving one precedence over the other, if both params are specified we should throw an exception as it doens't make much sense.

**Comment by poiru** [comment]
@vitillo Done.

**Comment by vitillo** [comment]
Looks good, have you tested it with the "Hello world notebook" as well?

**Comment by poiru** [comment]
@vitillo Yep. I also verified that `EVENTLOOP_UI_LAG_EXP_MS` works when using the Aurora Histograms.json.

**Comment by vitillo** [comment]
Nice, thanks!

**Comment by vitillo** [comment]
I deployed the new version pypi.

**Pull request merged**
